<?php

return [
    'navItems' => [
        ['label' => 'Feed', 'path' => '/'],
        ['label' => 'Learning', 'path' => '/learning/tutor'],
        ['label' => 'Chats', 'path' => '/messages'],
        ['label' => 'Wallet', 'path' => '/wallet'],
        ['label' => 'Explore', 'path' => '/explore'],
        ['label' => 'Notifications', 'path' => '/notifications'],
        ['label' => 'Settings', 'path' => '/settings'],
    ],
    'quickStats' => [
        ['label' => 'Active students', 'value' => '128,420'],
        ['label' => 'Live study rooms', 'value' => '214'],
        ['label' => 'Weekly transactions', 'value' => '48,930'],
    ],
    'feedPosts' => [
        [
            'id' => 'thermo-note-drop',
            'author' => 'Ada Madu',
            'faculty' => 'Engineering',
            'content' => 'Uploaded a full Thermodynamics problem pack to Study Hub and opened a live revision room for 8:00 PM. Everyone in 300L can join.',
            'tags' => ['Study Hub', 'Engineering', 'Live Class'],
            'likes' => 2840,
            'comments' => 426,
            'shares' => 188,
        ],
        [
            'id' => 'campus-shuttle',
            'author' => 'Campus Updates',
            'faculty' => 'Official',
            'content' => 'Shuttle routing for the science complex has been updated. Students in morning labs should check the revised stops before 7:30 AM.',
            'tags' => ['Transport', 'Announcements'],
            'likes' => 1730,
            'comments' => 98,
            'shares' => 230,
        ],
    ],
    'stories' => [
        ['title' => 'Exam venue moved', 'context' => 'CSC 305 now holds at ETF Hall by 10 AM.'],
        ['title' => 'Design meetup', 'context' => 'Creative club hosts portfolio reviews this evening.'],
        ['title' => 'Quick chemistry reel', 'context' => '15-second reaction memory trick trending now.'],
    ],
    'reels' => [
        ['title' => 'Organic Chemistry in 30 seconds', 'creator' => 'Favour Aina', 'views' => '82k'],
        ['title' => 'Hostel budgeting tips', 'creator' => 'David Nwosu', 'views' => '46k'],
        ['title' => 'Exam week desk setup', 'creator' => 'Tobi Joel', 'views' => '33k'],
    ],
    'events' => [
        ['name' => 'Campus Innovation Night', 'time' => 'Friday · 5:00 PM', 'venue' => 'Main Auditorium'],
        ['name' => 'Medical Student Hangout', 'time' => 'Saturday · 2:00 PM', 'venue' => 'Faculty Lawn'],
        ['name' => 'Backend Career Workshop', 'time' => 'Monday · 11:00 AM', 'venue' => 'ICT Hall'],
    ],
    'confessions' => [
        'I understand lectures better from study groups than from slides alone.',
        "Who has a good explanation for Laplace transforms that doesn't feel abstract?",
        'I need courage to present my final-year project proposal next week.',
    ],
    'chatThreads' => [
        ['name' => 'CSC 300L Circle', 'lastMessage' => 'New PDF shared by the class admin', 'unread' => 4],
        ['name' => 'Product Design Hub', 'lastMessage' => 'Voice note on portfolio review is ready', 'unread' => 1],
        ['name' => 'Room 14 Hostel Group', 'lastMessage' => 'Water schedule updated for tonight', 'unread' => 0],
    ],
    'directMessages' => [
        ['sender' => 'You', 'text' => 'Can you send the revised MTH 301 outline?'],
        ['sender' => 'Zara', 'text' => "Sending it now. Also added the lecturer's hint sheet."],
        ['sender' => 'You', 'text' => "Perfect. I'll review it before the quiz generator run."],
    ],
    'groupMessages' => [
        ['sender' => 'Admin', 'text' => 'Pinned the AI Tutor revision prompts for the group.'],
        ['sender' => 'Philip', 'text' => "Let's meet inside the live class room by 8 PM."],
        ['sender' => 'Mira', 'text' => 'I uploaded the shared flashcards for current electricity.'],
    ],
    'tutorMessages' => [
        ['role' => 'user', 'text' => "Explain Bernoulli's theorem with a hostel water tank example."],
        ['role' => 'assistant', 'text' => 'Think about water stored high in a tank above the hostel. As it drops through the pipe, gravitational potential reduces while flow speed increases.'],
    ],
    'studyMaterials' => [
        ['title' => 'CSC 305 System Analysis Slides', 'type' => 'PDF', 'status' => 'Bookmarked'],
        ['title' => 'GST 202 Civic Structure Notes', 'type' => 'Notes', 'status' => 'Saved'],
        ['title' => 'PHY 201 Recorded Revision Class', 'type' => 'Recording', 'status' => 'Available'],
    ],
    'courseModules' => [
        ['title' => 'Requirements Modeling', 'progress' => '80%'],
        ['title' => 'Feasibility Analysis', 'progress' => '63%'],
        ['title' => 'System Documentation', 'progress' => '42%'],
    ],
    'flashcards' => [
        ['front' => 'OSI Layer 3', 'back' => 'Network layer handles routing and logical addressing.'],
        ['front' => 'Bernoulli idea', 'back' => 'Pressure, velocity, and height stay related in fluid flow.'],
        ['front' => 'CPU scheduling', 'back' => 'Allocates processor time across waiting processes.'],
    ],
    'liveClasses' => [
        ['title' => 'Thermodynamics Drill Session', 'access' => 'Free', 'time' => 'Today · 8:00 PM'],
        ['title' => 'Frontend Portfolio Review', 'access' => 'Paid', 'time' => 'Tomorrow · 6:00 PM'],
        ['title' => 'Statistics Problem Walkthrough', 'access' => 'Free', 'time' => 'Wednesday · 7:30 PM'],
    ],
    'achievements' => [
        ['name' => '9-Day Streak', 'detail' => 'Logged in and completed study actions every day this week.'],
        ['name' => 'Top Contributor', 'detail' => 'Shared three high-value academic resources in one month.'],
        ['name' => 'Reel Educator', 'detail' => 'Passed 50k views on educational short-form content.'],
    ],
    'leaderboard' => [
        ['name' => 'Zara Thomas', 'xp' => 14220],
        ['name' => 'David Nwosu', 'xp' => 13940],
        ['name' => 'Philip Kazah', 'xp' => 12480],
        ['name' => 'Mira Bello', 'xp' => 12010],
    ],
    'walletSummary' => [
        'balance' => '0 Coins',
        'rewards' => '0 redeemed',
        'gifts' => '0 gifts sent',
    ],
    'transactions' => [],
    'paymentMethods' => [
        ['id' => 'bank', 'label' => 'Bank Transfer', 'note' => 'Great for manual settlement confirmation.'],
        ['id' => 'paystack', 'label' => 'Paystack', 'note' => 'Ready for future hosted checkout integration.'],
        ['id' => 'card', 'label' => 'Card', 'note' => 'Reserved for direct processor handoff by backend.'],
    ],
    'paymentAccountDetails' => [
        'accountNumber' => 'No live account',
        'bankName' => 'Unavailable',
        'accountName' => '',
        'note' => 'Wallet details will appear when real wallet and payment services are activated.',
    ],
    'jobs' => [
        ['id' => 'frontend-intern', 'title' => 'Frontend Engineering Intern', 'type' => 'Hybrid · Lagos · 3 months', 'summary' => 'Work on student-facing product features with a fast-moving product team.'],
        ['id' => 'campus-creator', 'title' => 'Campus Content Creator', 'type' => 'Remote · Flexible', 'summary' => 'Create short educational reels and community campaigns.'],
    ],
    'suggestions' => [
        'Trending students in Faculty of Science',
        'Recommended study groups for 300L Computer Science',
        'Popular live classes this week',
        'Opportunities matched to your skills',
    ],
    'notifications' => [
        ['title' => 'Live class begins in 18 minutes', 'tone' => 'info'],
        ['title' => 'Your wallet purchase is awaiting backend account details', 'tone' => 'warning'],
        ['title' => 'New reply in CSC 300L Circle', 'tone' => 'success'],
    ],
    'referrals' => [
        ['name' => 'Esther Paul', 'status' => 'Signed up', 'reward' => '150 coins'],
        ['name' => 'Samuel Joseph', 'status' => 'Verified', 'reward' => '300 coins'],
        ['name' => 'Grace Ibrahim', 'status' => 'Pending verification', 'reward' => 'Awaiting'],
    ],
    'suggestedUsers' => [
        [
            'id' => 'zara-thomas',
            'name' => 'Zara Thomas',
            'faculty' => 'Science',
            'department' => 'Computer Science',
            'bio' => 'Shares revision sheets, AI Tutor prompts, and weekly study recaps.',
            'mutuals' => 12,
            'followers' => 4200,
            'verified' => true,
        ],
        [
            'id' => 'mira-bello',
            'name' => 'Mira Bello',
            'faculty' => 'Engineering',
            'department' => 'Electrical Engineering',
            'bio' => 'Hosts lab prep sessions and uploads clean flashcard decks.',
            'mutuals' => 7,
            'followers' => 3150,
            'verified' => true,
        ],
        [
            'id' => 'david-nwosu',
            'name' => 'David Nwosu',
            'faculty' => 'Management Sciences',
            'department' => 'Accounting',
            'bio' => 'Breaks down finance concepts and posts simple budgeting reels.',
            'mutuals' => 9,
            'followers' => 2860,
            'verified' => false,
        ],
        [
            'id' => 'favour-aina',
            'name' => 'Favour Aina',
            'faculty' => 'Medicine',
            'department' => 'Anatomy',
            'bio' => 'Runs anatomy cram sessions and organizes exam-week check-ins.',
            'mutuals' => 5,
            'followers' => 1980,
            'verified' => true,
        ],
    ],
];
